name: "Approve test 1"

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  checkout:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        continue-on-error: true
      - name: Show info
        run: ls -a
  approve: 
    name: "Request approval"
    needs: checkout
    environment: test_approve_1
    runs-on: ubuntu-latest
