name: "Approve test 1"

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  checkout:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        continue-on-error: true
      - name: Show info
        run: ls -a
  approve: 
    name: "Request approval"
    needs: checkout
    environment: test_approve_1
    runs-on: ubuntu-latest
    steps:
      - name: workflow dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: approval-2.yml
          repo: FJ-AkihiroYamada/test-approval-2
          ref: main
          token: ${{ secrets.MY_PAT }}
          inputs: '{ "greeting": "hello" }'